name: Lint Python Code

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Run Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
       
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main         # Specify the default branch
          
